import { useEffect, useRef, useState } from 'react'
import { getMatches } from './api/matches'
import { getCatalog } from './api/catalog'
import { login } from './api/auth'
import { getCommentary, getCurrentInnings, getScorecard } from './api/scoring'
import { subscribeToMatch } from './api/liveMatch'
import { getNews } from './api/news'
import ScorerDashboard from './components/ScorerDashboard'
import CataloguePage from './components/CataloguePage'
import CatalogueDetail from './components/CatalogueDetail'
import NewsArticle from './components/NewsArticle'
import AdminTeams from './components/AdminTeams'
import AdminPlayers from './components/AdminPlayers'
import AdminVenues from './components/AdminVenues'
import AdminTournaments from './components/AdminTournaments'
import AdminMatches from './components/AdminMatches'
import AdminNews from './components/AdminNews'
import AdminOverview from './components/AdminOverview'
import AdminUsers from './components/AdminUsers'
import './App.css'
const nav=['Home','Matches','Teams','Players','Tournaments','News'];const preview=[{id:'live',status:'LIVE',teams:'India vs Australia',score:'186/4',overs:'19.2 overs'},{id:'upcoming',status:'UPCOMING',teams:'England vs South Africa',score:'Starts 19:30',overs:'The Oval'},{id:'result',status:'RESULT',teams:'Mumbai vs Chennai',score:'172/6',overs:'Mumbai won by 5 wickets'}];
export default function App(){const [page,setPage]=useState('Home'),[selected,setSelected]=useState(null),[catalogueItem,setCatalogueItem]=useState(null),[newsSlug,setNewsSlug]=useState(null),[open,setOpen]=useState(false),[admin,setAdmin]=useState(false),[scorer,setScorer]=useState(false);const go=x=>{setPage(x);setSelected(null);setCatalogueItem(null);setNewsSlug(null);setOpen(false)};return <><header><button className="brand" onClick={()=>go('Home')}>● CREASE</button><button className="menu" onClick={()=>setOpen(!open)}>☰</button><nav className={open?'open':''}>{nav.map(x=><button className={page===x?'active':''} onClick={()=>go(x)} key={x}>{x}</button>)}<button onClick={()=>setScorer(true)}>Score</button><button className="login" onClick={()=>setAdmin(true)}>Admin</button></nav></header>{scorer?<ScorerDashboard close={()=>setScorer(false)}/>:admin?<AdminDashboard close={()=>setAdmin(false)}/>:selected?<Centre match={selected} back={()=>setSelected(null)}/>:catalogueItem?<CatalogueDetail selection={catalogueItem} back={()=>setCatalogueItem(null)}/>:newsSlug?<NewsArticle slug={newsSlug} back={()=>setNewsSlug(null)}/>:page==='Home'?<Home go={go} select={setSelected}/>:page==='Matches'?<Matches select={setSelected}/>:page==='News'?<News select={setNewsSlug}/>:['Teams','Players','Tournaments'].includes(page)?<CataloguePage kind={page} select={setCatalogueItem}/>:<Listing title={page}/>}</>}
function Home({go,select}){return <main><section className="hero"><p>CRICKET, EVERY BALL</p><h1>Follow the game<br/><i>as it happens.</i></h1><span>Live scores, match stories and the players shaping every over.</span><button className="cta" onClick={()=>go('Matches')}>Explore live cricket →</button><aside><small>LIVE · 2ND INNINGS</small><h2>IND <b>186/4</b></h2><p>19.2 overs · Target 210</p><strong>1　4　0　W　6　1</strong><button onClick={()=>select(preview[0])}>Open match centre →</button></aside></section><Cards matches={preview} select={select}/><section className="spot"><div><p>TOURNAMENT SPOTLIGHT</p><h2>Where every<br/><i>run tells a story.</i></h2><button onClick={()=>go('Tournaments')}>Explore tournaments →</button></div><div className="table"><b>IPL 2026</b><p>01 Mumbai Indians <strong>16</strong></p><p>02 Chennai Super Kings <strong>15</strong></p><p>03 Royal Challengers <strong>14</strong></p></div></section></main>}
function Matches({select}){const [items,setItems]=useState([]),[status,setStatus]=useState('loading');useEffect(()=>{getMatches().then(d=>{setItems((d.items||[]).map(m=>({id:m.id,status:m.status,teams:`${m.homeTeam.name} vs ${m.awayTeam.name}`,score:'Scheduled',overs:new Date(m.startsAt).toLocaleString(),format:m.format,tournamentName:m.tournamentName,venueName:m.venueName,startsAt:m.startsAt,oversLimit:m.oversLimit,notes:m.notes})));setStatus('ready')}).catch(()=>{setItems(preview);setStatus('preview')})},[]);return <main className="listing"><p>CRICKET CENTRE</p><h1>Matches</h1>{status==='loading'&&<div className="state-card">Loading matches…</div>}{status==='preview'&&<small className="notice">Local API unavailable — showing the design preview.</small>}{status==='ready'&&items.length===0&&<div className="state-card">No matches are scheduled yet.</div>}{(status==='preview'||items.length>0)&&<Cards matches={items} select={select}/>}</main>}
function Cards({matches,select}){return <section className="match-section"><p>ON THE PITCH</p><h2>Matches that matter</h2><div className="cards">{matches.map(m=><button className="match-card" onClick={()=>select(m)} key={m.id}><small>{m.status}</small><h3>{m.teams}</h3><b>{m.score}</b><p>{m.overs}</p><span>Open match centre →</span></button>)}</div></section>}
function News({select}){const [articles,setArticles]=useState([]),[status,setStatus]=useState('loading');useEffect(()=>{getNews().then(data=>{setArticles(data);setStatus('ready')}).catch(()=>setStatus('error'))},[]);return <main className="listing"><p>CRICKET STORIES</p><h1>News</h1>{status==='loading'&&<div className="state-card">Loading stories…</div>}{status==='error'&&<div className="state-card">News is unavailable while the local API is offline.</div>}{status==='ready'&&articles.length===0&&<div className="state-card">No stories have been published yet.</div>}{articles.length>0&&<div className="news-grid">{articles.map(article=><button className="news-card news-button" onClick={()=>select(article.slug)} key={article.id}><small>{new Date(article.publishedAt).toLocaleDateString()}</small><h2>{article.title}</h2><p>{article.summary}</p><b>{article.isFeatured?'FEATURED · ':''}Read story →</b></button>)}</div>}</main>}
function Listing({title}){return <main className="listing"><p>CRICKET CENTRE</p><h1>{title}</h1><div>This public module is ready to connect to the Cricket Sports API.</div></main>}
function Centre({match,back}){const [tab,setTab]=useState('Live');const [state,setState]=useState(null);const [celebration,setCelebration]=useState(null);const sequence=useRef(-1);const show=text=>{setCelebration(text);window.setTimeout(()=>setCelebration(null),1450)};useEffect(()=>{getCurrentInnings(match.id).then(current=>{if(current){sequence.current=current.eventSequence;setState(current)}});return subscribeToMatch(match.id,{onScore:event=>{if(event.eventSequence>sequence.current){sequence.current=event.eventSequence;setState(event)}},onDelivery:event=>{if(event.state.eventSequence>sequence.current){sequence.current=event.state.eventSequence;setState(event.state);if(event.isWicket)show('WICKET!');else if(event.runsOffBat===6)show('SIX!');else if(event.runsOffBat===4)show('FOUR!')}},onMatchCompleted:()=>show('MATCH COMPLETE')})},[match.id]);const runs=state?.totalRuns;const wickets=state?.wickets;const overs=state?`${state.overNumber}.${state.ballInOver}`:'—';return <main className="centre">{celebration&&<div className={`event-overlay ${celebration==='WICKET!'?'wicket-event':''}`}><span>{celebration}</span></div>}<button className="back" onClick={back}>← All matches</button><section className="scoreboard"><small>{state?'LIVE · CURRENT INNINGS':'MATCH CENTRE'}</small><h1>{match.teams}</h1><div className="score-line"><span>Score</span><strong>{state?`${runs}/${wickets}`:'—'}</strong><span>{overs} overs</span></div><p>{state?'Live score supplied by the scoring engine.':'No active innings is being scored yet.'}</p>{state&&<small className="live-sync">Live update received · event #{state.eventSequence}</small>}</section><div className="tabs">{['Live','Scorecard','Commentary','Statistics','Info'].map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Live'?<Live matchId={match.id} state={state}/>:tab==='Scorecard'?<Scorecard matchId={match.id}/>:tab==='Commentary'?<Commentary matchId={match.id}/>:tab==='Statistics'?<Stats matchId={match.id}/>:<Info match={match}/>}</main>}
function Live({matchId,state}){const [players,setPlayers]=useState([]);const [deliveries,setDeliveries]=useState([]);useEffect(()=>{getCatalog('players').then(data=>setPlayers(data.items||[])).catch(()=>{});getCommentary(matchId).then(setDeliveries).catch(()=>{})},[matchId,state?.eventSequence]);if(!state)return <section className="panel"><p>No active innings is being scored yet.</p></section>;const name=id=>players.find(player=>player.id===id)?.fullName||'Loading player…';const recent=deliveries.slice(0,6).reverse();const ball=item=>item.isWicket?'W':item.extraType!==0?'E':String(item.runsOffBat);return <section className="panel"><div className="current"><article><small>STRIKER</small><h2>{name(state.strikerId)}</h2><p>Currently at the crease</p></article><article><small>NON-STRIKER</small><h2>{name(state.nonStrikerId)}</h2><p>Currently at the crease</p></article><article><small>BOWLER</small><h2>{name(state.bowlerId)}</h2><p>Current bowler</p></article></div><h3>Recent balls</h3>{recent.length?<div className="balls">{recent.map((item,index)=><b className={item.isWicket?'wicket':item.runsOffBat===4?'four':item.runsOffBat===6?'six':''} key={index}>{ball(item)}</b>)}</div>:<p>No deliveries recorded yet.</p>}</section>}
function Scorecard({matchId}){const [innings,setInnings]=useState([]);const [status,setStatus]=useState('loading');useEffect(()=>{getScorecard(matchId).then(data=>{setInnings(data);setStatus('ready')}).catch(()=>setStatus('error'))},[matchId]);if(status==='loading')return <section className="panel"><p>Loading scorecard…</p></section>;if(status==='error')return <section className="panel"><p>Scorecard is unavailable.</p></section>;if(!innings.length)return <section className="panel"><p>No innings has been scored yet.</p></section>;return <section className="panel">{innings.map(innings=> <div className="innings-card" key={innings.number}><h2>{innings.battingTeamName} <b>{innings.totalRuns}/{innings.wickets}</b></h2><p>{Math.floor(innings.legalBalls/6)}.{innings.legalBalls%6} overs · Extras {innings.extras} · {innings.isComplete?'Completed':'Live'}</p><table><thead><tr><th>Batting</th><th>Status</th><th>R</th><th>B</th><th>4s</th><th>6s</th></tr></thead><tbody>{innings.batting.map(player=><tr key={player.playerName}><td>{player.playerName}</td><td>{player.isOut?'Out':'Not out'}</td><td>{player.runs}</td><td>{player.balls}</td><td>{player.fours}</td><td>{player.sixes}</td></tr>)}</tbody></table><h3>Bowling</h3><table><thead><tr><th>Player</th><th>O</th><th>R</th><th>W</th></tr></thead><tbody>{innings.bowling.map(player=><tr key={player.playerName}><td>{player.playerName}</td><td>{Math.floor(player.legalBalls/6)}.{player.legalBalls%6}</td><td>{player.runsConceded}</td><td>{player.wickets}</td></tr>)}</tbody></table></div>)}</section>}
function Commentary({matchId}){const [items,setItems]=useState([]);const [status,setStatus]=useState('loading');useEffect(()=>{getCommentary(matchId).then(data=>{setItems(data);setStatus('ready')}).catch(()=>setStatus('error'))},[matchId]);if(status==='loading')return <section className="panel"><p>Loading commentary…</p></section>;if(status==='error')return <section className="panel"><p>Commentary is unavailable.</p></section>;if(!items.length)return <section className="panel"><p>No deliveries have been recorded yet.</p></section>;return <section className="panel commentary">{items.map((item,index)=>{const label=item.isWicket?'WICKET':item.runsOffBat===6?'SIX':item.runsOffBat===4?'FOUR':item.extraType!==0?'EXTRA':`${item.runsOffBat} RUN${item.runsOffBat===1?'':'S'}`;return <article key={`${item.inningsNumber}-${index}`}><b>{item.overNumber}.{item.ballNumber}</b><div><strong>{label}</strong><p>{item.commentary || `Innings ${item.inningsNumber}: ${label.toLowerCase()}.`}</p></div></article>})}</section>}
function Stats({matchId}){const [innings,setInnings]=useState([]);const [status,setStatus]=useState('loading');useEffect(()=>{getScorecard(matchId).then(data=>{setInnings(data);setStatus('ready')}).catch(()=>setStatus('error'))},[matchId]);if(status==='loading')return <section className="panel"><p>Loading statistics…</p></section>;if(status==='error')return <section className="panel"><p>Statistics are unavailable.</p></section>;if(!innings.length)return <section className="panel"><p>No innings has been scored yet.</p></section>;return <section className="panel stats"><h2>Match statistics</h2><div className="stat-grid">{innings.map(item=>{const fours=item.batting.reduce((total,player)=>total+player.fours,0);const sixes=item.batting.reduce((total,player)=>total+player.sixes,0);const rate=item.legalBalls?(item.totalRuns/(item.legalBalls/6)).toFixed(2):'0.00';return <article key={item.number}><h3>{item.battingTeamName}</h3><p><b>{item.totalRuns}/{item.wickets}</b> in {Math.floor(item.legalBalls/6)}.{item.legalBalls%6} overs</p><dl><div><dt>Run rate</dt><dd>{rate}</dd></div><div><dt>Fours</dt><dd>{fours}</dd></div><div><dt>Sixes</dt><dd>{sixes}</dd></div><div><dt>Extras</dt><dd>{item.extras}</dd></div></dl></article>})}</div></section>}
function Info({match}){const formats=['Test','ODI','T20','T10'];const status=typeof match.status==='number'?['Scheduled','Live','Completed','Cancelled','Abandoned'][match.status]:match.status;return <section className="panel info"><h2>Match information</h2><p><b>Format</b><span>{typeof match.format==='number'?formats[match.format]:match.format||'Not set'}</span></p><p><b>Status</b><span>{status||'Not set'}</span></p><p><b>Tournament</b><span>{match.tournamentName||'Not set'}</span></p><p><b>Venue</b><span>{match.venueName||'Not set'}</span></p><p><b>Start time</b><span>{match.startsAt?new Date(match.startsAt).toLocaleString():'Not set'}</span></p><p><b>Overs limit</b><span>{match.oversLimit||'Not set'}</span></p>{match.notes&&<p><b>Notes</b><span>{match.notes}</span></p>}</section>}
function AdminDashboard({close}){const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('crease-session')||'null'));const [area,setArea]=useState('Overview');const [error,setError]=useState('');const signIn=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await login(f.get('email'),f.get('password'));localStorage.setItem('crease-session',JSON.stringify(result));setSession(result)}catch{setError('Unable to sign in. Check the API, database, and account.')}};if(!session)return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><form onSubmit={signIn}><p>ADMIN ACCESS</p><h1>Control centre</h1><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label>{error&&<small>{error}</small>}<button className="cta">Sign in →</button><span>Only Admin-role accounts can enter.</span></form></main>;if(!session.roles?.includes('Admin'))return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><div className="denied"><p>ACCESS RESTRICTED</p><h1>Admin role required</h1><span>This account cannot manage cricket data.</span><button onClick={()=>{localStorage.removeItem('crease-session');setSession(null)}}>Use another account</button></div></main>;const sections=['Overview','Teams','Players','Tournaments','Venues','Matches','News','Users'];return <main className="admin"><aside><b>● CREASE ADMIN</b>{sections.map(x=><button className={area===x?'active':''} onClick={()=>setArea(x)} key={x}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('crease-session');setSession(null)}}>Sign out</button></aside><section><header><div><p>ADMIN DASHBOARD</p><h1>{area}</h1></div><button className="login" onClick={close}>View site</button></header>{area==='Overview'?<AdminOverview/>:area==='Teams'?<AdminTeams session={session}/>:area==='Players'?<AdminPlayers session={session}/>:area==='Venues'?<AdminVenues session={session}/>:area==='Tournaments'?<AdminTournaments session={session}/>:area==='Matches'?<AdminMatches session={session}/>:area==='News'?<AdminNews session={session}/>:area==='Users'?<AdminUsers session={session}/>:<Management area={area}/>}</section></main>}
function Overview(){return <><div className="admin-cards">{[['Total matches','24'],['Live matches','3'],['Total players','186'],['Total teams','16'],['Tournaments','4']].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>Updated from API</span></article>)}</div><div className="admin-block"><h2>Today’s activity</h2><p>Manage catalogue data through the protected APIs. Destructive actions should be confirmed before submission.</p></div></>}
function Management({area}){return <div className="admin-block"><div className="manage-head"><h2>Manage {area}</h2><button className="cta">+ Add {area.slice(0,-1)}</button></div><input placeholder={`Search ${area.toLowerCase()}…`}/><div className="admin-empty"><b>{area} management</b><p>This authorized view is ready to connect to the protected CRUD endpoint.</p></div></div>}
