import { useEffect, useRef, useState } from 'react'
import { getMatches } from './api/matches'
import { login } from './api/auth'
import { subscribeToMatch } from './api/liveMatch'
import './App.css'
const nav=['Home','Matches','Teams','Players','Tournaments'];const preview=[{id:'live',status:'LIVE',teams:'India vs Australia',score:'186/4',overs:'19.2 overs'},{id:'upcoming',status:'UPCOMING',teams:'England vs South Africa',score:'Starts 19:30',overs:'The Oval'},{id:'result',status:'RESULT',teams:'Mumbai vs Chennai',score:'172/6',overs:'Mumbai won by 5 wickets'}];
export default function App(){const [page,setPage]=useState('Home'),[selected,setSelected]=useState(null),[open,setOpen]=useState(false),[admin,setAdmin]=useState(false);const go=x=>{setPage(x);setSelected(null);setOpen(false)};return <><header><button className="brand" onClick={()=>go('Home')}>● CREASE</button><button className="menu" onClick={()=>setOpen(!open)}>☰</button><nav className={open?'open':''}>{nav.map(x=><button className={page===x?'active':''} onClick={()=>go(x)} key={x}>{x}</button>)}<button className="login" onClick={()=>setAdmin(true)}>Admin</button></nav></header>{admin?<AdminDashboard close={()=>setAdmin(false)}/>:selected?<Centre match={selected} back={()=>setSelected(null)}/>:page==='Home'?<Home go={go} select={setSelected}/>:page==='Matches'?<Matches select={setSelected}/>:<Listing title={page}/>}</>}
function Home({go,select}){return <main><section className="hero"><p>CRICKET, EVERY BALL</p><h1>Follow the game<br/><i>as it happens.</i></h1><span>Live scores, match stories and the players shaping every over.</span><button className="cta" onClick={()=>go('Matches')}>Explore live cricket →</button><aside><small>LIVE · 2ND INNINGS</small><h2>IND <b>186/4</b></h2><p>19.2 overs · Target 210</p><strong>1　4　0　W　6　1</strong><button onClick={()=>select(preview[0])}>Open match centre →</button></aside></section><Cards matches={preview} select={select}/><section className="spot"><div><p>TOURNAMENT SPOTLIGHT</p><h2>Where every<br/><i>run tells a story.</i></h2><button onClick={()=>go('Tournaments')}>Explore tournaments →</button></div><div className="table"><b>IPL 2026</b><p>01 Mumbai Indians <strong>16</strong></p><p>02 Chennai Super Kings <strong>15</strong></p><p>03 Royal Challengers <strong>14</strong></p></div></section></main>}
function Matches({select}){const [items,setItems]=useState(preview),[note,setNote]=useState('');useEffect(()=>{getMatches().then(d=>{if(d.items?.length)setItems(d.items.map(m=>({id:m.id,status:m.status,teams:`${m.homeTeam.name} vs ${m.awayTeam.name}`,score:'Scheduled',overs:new Date(m.startsAt).toLocaleString()})))}).catch(()=>setNote('Showing the design preview while the local API is unavailable.'))},[]);return <main className="listing"><p>CRICKET CENTRE</p><h1>Matches</h1>{note&&<small className="notice">{note}</small>}<Cards matches={items} select={select}/></main>}
function Cards({matches,select}){return <section className="match-section"><p>ON THE PITCH</p><h2>Matches that matter</h2><div className="cards">{matches.map(m=><button className="match-card" onClick={()=>select(m)} key={m.id}><small>{m.status}</small><h3>{m.teams}</h3><b>{m.score}</b><p>{m.overs}</p><span>Open match centre →</span></button>)}</div></section>}
function Listing({title}){return <main className="listing"><p>CRICKET CENTRE</p><h1>{title}</h1><div>This public module is ready to connect to the Cricket Sports API.</div></main>}
function Centre({match,back}){const [tab,setTab]=useState('Live');const [state,setState]=useState(null);const [celebration,setCelebration]=useState(null);const sequence=useRef(-1);const show=text=>{setCelebration(text);window.setTimeout(()=>setCelebration(null),1450)};useEffect(()=>subscribeToMatch(match.id,{onScore:event=>{if(event.eventSequence>sequence.current){sequence.current=event.eventSequence;setState(event)}},onDelivery:event=>{if(event.state.eventSequence>sequence.current){sequence.current=event.state.eventSequence;setState(event.state);if(event.isWicket)show('WICKET!');else if(event.runsOffBat===6)show('SIX!');else if(event.runsOffBat===4)show('FOUR!')}},onMatchCompleted:()=>show('MATCH COMPLETE')}),[match.id]);const runs=state?.totalRuns??186;const wickets=state?.wickets??4;const overs=state?`${state.overNumber}.${state.ballInOver}`:'19.2';return <main className="centre">{celebration&&<div className={`event-overlay ${celebration==='WICKET!'?'wicket-event':''}`}><span>{celebration}</span></div>}<button className="back" onClick={back}>← All matches</button><section className="scoreboard"><small>LIVE · 2ND INNINGS</small><h1>{match.teams}</h1><div className="score-line"><span>INDIA</span><strong>{runs}/{wickets}</strong><span>{overs} overs</span></div><p>Current run rate <b>9.62</b> · Target <b>210</b> · Need 24 runs from 4 balls</p>{state&&<small className="live-sync">Live update received · event #{state.eventSequence}</small>}</section><div className="tabs">{['Live','Scorecard','Commentary','Statistics','Info'].map(x=><button className={tab===x?'selected':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='Live'?<Live/>:tab==='Scorecard'?<Scorecard/>:tab==='Commentary'?<Commentary/>:tab==='Statistics'?<Stats/>:<Info/>}</main>}
function Live(){return <section className="panel"><div className="current"><article><small>STRIKER</small><h2>Virat Kohli <b>74*</b></h2><p>52 balls · 7 fours · 2 sixes</p></article><article><small>BOWLER</small><h2>Pat Cummins <b>3/38</b></h2><p>3.2 overs · Economy 11.40</p></article></div><h3>Recent balls</h3><div className="balls"><b>1</b><b className="four">4</b><b>0</b><b className="wicket">W</b><b className="six">6</b><b>1</b></div><p className="data-note">Official live score data will be supplied by the scoring engine in Module 6.</p></section>}
function Scorecard(){return <section className="panel"><h2>India batting</h2><table><thead><tr><th>Player</th><th>Dismissal</th><th>R</th><th>B</th></tr></thead><tbody>{[['Rohit Sharma','c Smith b Starc','42','31'],['Shubman Gill','lbw b Cummins','28','22'],['Virat Kohli','not out','74','52'],['KL Rahul','not out','31','20']].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table><h2>Australia bowling</h2><table><tbody><tr><td>Pat Cummins</td><td>3.2 overs</td><td>38 runs</td><td>3 wickets</td></tr><tr><td>Mitchell Starc</td><td>4 overs</td><td>41 runs</td><td>1 wicket</td></tr></tbody></table></section>}
function Commentary(){return <section className="panel commentary">{[['19.3','SIX!','Kohli picks the slower ball and sends it over long-on.'],['19.2','WICKET!','A sharp catch at deep mid-wicket changes the equation.'],['19.1','FOUR!','A precise cover drive beats the infield.']].map(x=><article key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div></article>)}</section>}
function Stats(){return <section className="panel stats"><h2>Match statistics</h2><div className="chart">{[62,76,48,92,67].map((x,i)=><div style={{height:`${x}%`}} key={i}><span>{x}</span></div>)}</div><p>Runs per over · official chart data will be enabled with the scoring feed.</p></section>}
function Info(){return <section className="panel info"><h2>Match information</h2><p><b>Format</b><span>T20 International</span></p><p><b>Venue</b><span>Melbourne Cricket Ground</span></p><p><b>Start time</b><span>20 August 2026, 19:30 IST</span></p></section>}
function AdminDashboard({close}){const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('crease-session')||'null'));const [area,setArea]=useState('Overview');const [error,setError]=useState('');const signIn=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await login(f.get('email'),f.get('password'));localStorage.setItem('crease-session',JSON.stringify(result));setSession(result)}catch{setError('Unable to sign in. Check the API, database, and account.')}};if(!session)return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><form onSubmit={signIn}><p>ADMIN ACCESS</p><h1>Control centre</h1><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label>{error&&<small>{error}</small>}<button className="cta">Sign in →</button><span>Only Admin-role accounts can enter.</span></form></main>;if(!session.roles?.includes('Admin'))return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><div className="denied"><p>ACCESS RESTRICTED</p><h1>Admin role required</h1><span>This account cannot manage cricket data.</span><button onClick={()=>{localStorage.removeItem('crease-session');setSession(null)}}>Use another account</button></div></main>;const sections=['Overview','Teams','Players','Tournaments','Venues','Matches','News','Users'];return <main className="admin"><aside><b>● CREASE ADMIN</b>{sections.map(x=><button className={area===x?'active':''} onClick={()=>setArea(x)} key={x}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('crease-session');setSession(null)}}>Sign out</button></aside><section><header><div><p>ADMIN DASHBOARD</p><h1>{area}</h1></div><button className="login" onClick={close}>View site</button></header>{area==='Overview'?<Overview/>:<Management area={area}/>}</section></main>}
function Overview(){return <><div className="admin-cards">{[['Total matches','24'],['Live matches','3'],['Total players','186'],['Total teams','16'],['Tournaments','4']].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>Updated from API</span></article>)}</div><div className="admin-block"><h2>Today’s activity</h2><p>Manage catalogue data through the protected APIs. Destructive actions should be confirmed before submission.</p></div></>}
function Management({area}){return <div className="admin-block"><div className="manage-head"><h2>Manage {area}</h2><button className="cta">+ Add {area.slice(0,-1)}</button></div><input placeholder={`Search ${area.toLowerCase()}…`}/><div className="admin-empty"><b>{area} management</b><p>This authorized view is ready to connect to the protected CRUD endpoint.</p></div></div>}
