import { useEffect, useMemo, useState } from 'react'
import { getMatches } from '../api/matches'
import { startInnings, recordDelivery, undoDelivery, endInnings, endMatch } from '../api/scoring'
import { login } from '../api/auth'

const API_BASE = import.meta.env.VITE_API_URL ?? 'https://localhost:44336'
const emptyDelivery = { runsOffBat: 0, extraRuns: 0, extraType: 0, isWicket: false, wicketType: null, dismissedPlayerId: null, incomingBatterId: null, commentary: null }

export default function ScorerDashboard({ close }) {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('crease-session') || 'null'))
  const [matches, setMatches] = useState([]), [players, setPlayers] = useState([]), [matchId, setMatchId] = useState(''), [state, setState] = useState(null), [message, setMessage] = useState('Loading available matches…'), [commentary, setCommentary] = useState('')
  useEffect(() => { Promise.all([getMatches(), fetch(`${API_BASE}/api/players?page=1&pageSize=100`).then(r => r.ok ? r.json() : Promise.reject())]).then(([matchData, playerData]) => { setMatches(matchData.items || []); setPlayers(playerData.items || []); setMessage('') }).catch(() => setMessage('Unable to load matches or players. Start the API and ensure its URL is set in VITE_API_URL.')) }, [])
  const match = matches.find(item => item.id === matchId); const batters = useMemo(() => players.filter(player => player.teamId === match?.homeTeam.id), [players, match]); const bowlers = useMemo(() => players.filter(player => player.teamId === match?.awayTeam.id), [players, match])
  const action = async (run) => { try { const result = await run(); if (result) setState(result); setMessage(''); } catch (error) { setMessage('Action rejected: check selected match, players, innings state, and role.') } }
  const start = event => { event.preventDefault(); const form = new FormData(event.currentTarget); action(() => startInnings(matchId, session.accessToken, { battingTeamId: match.homeTeam.id, strikerId: form.get('striker'), nonStrikerId: form.get('nonStriker'), bowlerId: form.get('bowler') })) }
  const delivery = payload => action(async () => { const result = await recordDelivery(matchId, session.accessToken, { ...emptyDelivery, ...payload, commentary: commentary.trim() || null }); setCommentary(''); return result })
  const score = runs => delivery({ runsOffBat: runs })
  const signIn = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await login(form.get('email'), form.get('password')); localStorage.setItem('crease-session', JSON.stringify(result)); setSession(result) } catch { setMessage('Unable to sign in.') } }
  if (!session) return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><form onSubmit={signIn}><p>SCORER ACCESS</p><h1>Scorer console</h1><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button className="cta">Sign in →</button></form></main>
  if (!session.roles?.some(role => role === 'Admin' || role === 'Scorer')) return <main className="admin-login"><button className="back" onClick={close}>← Back to site</button><div className="denied"><p>ACCESS RESTRICTED</p><h1>Scorer role required</h1><span>Use an account assigned Admin or Scorer.</span><button onClick={() => { localStorage.removeItem('crease-session'); setSession(null) }}>Use another account</button></div></main>
  return <main className="scorer"><header><div><p>LIVE SCORING</p><h1>Scorer console</h1></div><button className="login" onClick={close}>View site</button></header>{message && <div className="state-card">{message}</div>}<section className="scoring-select"><label>Match<select value={matchId} onChange={event => { setMatchId(event.target.value); setState(null) }}><option value="">Choose a match</option>{matches.map(item => <option value={item.id} key={item.id}>{item.homeTeam.name} vs {item.awayTeam.name}</option>)}</select></label></section>{match && !state && <form className="innings-form" onSubmit={start}><h2>Start innings · {match.homeTeam.name} batting</h2><label>Striker<select name="striker" required><option value="">Select player</option>{batters.map(player => <option value={player.id} key={player.id}>{player.fullName}</option>)}</select></label><label>Non-striker<select name="nonStriker" required><option value="">Select player</option>{batters.map(player => <option value={player.id} key={player.id}>{player.fullName}</option>)}</select></label><label>Bowler<select name="bowler" required><option value="">Select player</option>{bowlers.map(player => <option value={player.id} key={player.id}>{player.fullName}</option>)}</select></label><button className="cta">Start innings →</button></form>}{state && <section className="scoring-board"><div className="scoring-score"><small>CURRENT SCORE</small><b>{state.totalRuns}/{state.wickets}</b><span>{state.overNumber}.{state.ballInOver} overs</span></div><h2>Record delivery</h2><label className="commentary-input">Optional commentary for next delivery<input value={commentary} onChange={event => setCommentary(event.target.value)} placeholder="e.g. Driven through cover for four" /></label><div className="run-grid">{[0,1,2,3,4,6].map(run => <button onClick={() => score(run)} key={run}>{run}</button>)}</div><div className="scoring-actions"><button onClick={() => delivery({ extraRuns: 1, extraType: 1 })}>Wide</button><button onClick={() => delivery({ extraRuns: 1, extraType: 2 })}>No ball</button><button className="danger" onClick={() => action(() => undoDelivery(matchId, session.accessToken))}>Undo last ball</button><button onClick={() => action(() => endInnings(matchId, session.accessToken))}>End innings</button><button className="danger" onClick={() => action(() => endMatch(matchId, session.accessToken))}>End match</button></div></section>}</main>
}
